#!/bin/bash
set -euo pipefail

readonly HTTP_PORT=8080
readonly HTTP_RETRY_COUNT=10
readonly HTTP_CONNECT_TIMEOUT_SECONDS=2
readonly MCP_TIMEOUT_SECONDS=10
readonly SCHEMA_VALIDATE_URL_PATH="/v1/schema/validate-url"
readonly SERVER_INFO_URL_PATH="/v1/server-info"
readonly SITE_ONBOARDING_URL_PATH="/v1/site-onboarding-submissions"
readonly OPENAPI_PATH="/openapi.json"
readonly OPENAPI_VERSION="3.1.0"
readonly SERVER_INFO_OPERATION_ID="serverInfo"
TEST_CONTAINER_UID_GID="$(id -u):$(id -g)"
readonly TEST_CONTAINER_UID_GID
readonly TEST_MEMORY_LIMIT="512m"
readonly TEST_CPU_LIMIT="1"
readonly TEST_PIDS_LIMIT=128
readonly MCP_INITIALIZE_REQUEST='{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"rankrat-image-smoke","version":"0"}}}'
readonly TEST_HTTP_BEARER_SECRET="test-only-not-a-real-secret-value-000000000000"
readonly PRIVATE_SCHEMA_URL_REQUEST='{"url":"https://127.0.0.1/"}'
readonly PARENT_BASH_PROCESS_ID="$BASHPID"

log() {
	local level="$1"
	shift
	local timestamp
	timestamp=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
	printf '{"time":"%s","level":"%s","file":"%s","line":%d,"func":"%s","msg":"%s"}\n' \
		"$timestamp" "$level" "${BASH_SOURCE[1]##*/}" "${BASH_LINENO[0]}" \
		"${FUNCNAME[1]:-main}" "$*" >&2
}

usage() {
	printf 'usage: %s <production-image>\n' "${0##*/}" >&2
}

[[ "$#" -eq 1 ]] || {
	usage
	exit 2
}

temporary_directory=""
container_name=""
http_container_started=false

cleanup() {
	if [[ "$BASHPID" != "$PARENT_BASH_PROCESS_ID" ]]; then
		return
	fi
	if [[ "$http_container_started" == true ]]; then
		# This exact name is generated by this script and set only after docker run succeeds.
		docker rm -f "$container_name" >/dev/null 2>&1 || :
	fi
	if [[ -n "$temporary_directory" ]]; then
		rm -rf -- "$temporary_directory"
	fi
}

assert_test_mounts_exist() {
	[[ -d "$config_directory" ]] || {
		log ERROR "temporary configuration directory disappeared"
		exit 1
	}
	[[ -d "$secret_directory" ]] || {
		log ERROR "temporary secret directory disappeared"
		exit 1
	}
	[[ -d "$oauth_directory" ]] || {
		log ERROR "temporary OAuth directory disappeared"
		exit 1
	}
	[[ -f "$boundary_file" ]] || {
		log ERROR "temporary boundary file disappeared"
		exit 1
	}
}

log_http_container_output() {
	if ! docker logs "$container_name" >&2; then
		log WARN "could not retrieve the smoke container output"
	fi
}

on_error() {
	local exit_status=$?
	log ERROR "production image smoke failed exit=${exit_status}"
	exit "$exit_status"
}

trap cleanup EXIT
trap on_error ERR

readonly image_reference="$1"
script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly script_directory
project_directory="$(cd -- "$script_directory/.." && pwd)"
readonly project_directory
readonly boundary_example="$project_directory/config/boundaries.json.example"

temporary_directory=$(
	trap - EXIT ERR
	mktemp -d "$project_directory/.test-image.XXXXXX"
)
LOG_FILE="${LOG_FILE:-$temporary_directory/final-image.log}"
exec > >(tee -a "$LOG_FILE") 2>&1

[[ -f "$boundary_example" ]] || {
	log ERROR "public boundary example is missing"
	exit 1
}

readonly config_directory="$temporary_directory/config"
readonly secret_directory="$temporary_directory/secrets"
readonly oauth_directory="$temporary_directory/oauth"
readonly boundary_file="$config_directory/boundaries.json"
readonly curl_authorization_config="$temporary_directory/curl-authorization.conf"
mkdir "$config_directory" "$secret_directory" "$oauth_directory"
cp "$boundary_example" "$boundary_file"
printf '%s\n' "$TEST_HTTP_BEARER_SECRET" >"$secret_directory/test-http-bearer"
printf 'header = "Authorization: Bearer %s"\n' "$TEST_HTTP_BEARER_SECRET" \
	>"$curl_authorization_config"
chmod 755 "$temporary_directory" "$config_directory" "$secret_directory" "$oauth_directory"
chmod 600 "$secret_directory/test-http-bearer"
chmod 600 "$curl_authorization_config"
assert_test_mounts_exist

container_name="rankrat-final-image-$$-${RANDOM}"
container_security_args=(
	--init
	--user "$TEST_CONTAINER_UID_GID"
	--read-only
	--cap-drop=ALL
	--security-opt no-new-privileges:true
	--pids-limit "$TEST_PIDS_LIMIT"
	--memory "$TEST_MEMORY_LIMIT"
	--cpus "$TEST_CPU_LIMIT"
	--tmpfs "/tmp:rw,noexec,nosuid,size=32m"
	--mount "type=bind,src=$config_directory,dst=/run/config,readonly"
	--mount "type=bind,src=$secret_directory,dst=/run/secrets,readonly"
	--mount "type=bind,src=$oauth_directory,dst=/run/oauth,readonly"
	-e RANKRAT_BOUNDARY_FILE=/run/config/boundaries.json
	-e RANKRAT_SECRET_ROOT=/run/secrets
	-e RANKRAT_OAUTH_TOKEN_ROOT=/run/oauth
)
readonly -a container_security_args

log INFO "checking startup fails without an explicit boundary mount"
if docker run --rm --network none --init --user "$TEST_CONTAINER_UID_GID" --read-only \
	--cap-drop=ALL --security-opt no-new-privileges:true --pids-limit "$TEST_PIDS_LIMIT" \
	--memory "$TEST_MEMORY_LIMIT" --cpus "$TEST_CPU_LIMIT" \
	--tmpfs /tmp:rw,noexec,nosuid,size=32m "$image_reference" </dev/null; then
	log ERROR "image unexpectedly started without a boundary mount"
	exit 1
fi

assert_test_mounts_exist
log INFO "checking stdio MCP initialization without network access"
mcp_output=$(printf '%s\n' "$MCP_INITIALIZE_REQUEST" | timeout --kill-after=2s \
	"${MCP_TIMEOUT_SECONDS}s" docker run --rm -i --network none \
	"${container_security_args[@]}" "$image_reference")
grep -Fq '"protocolVersion"' <<<"$mcp_output" || {
	log ERROR "stdio MCP initialization did not return a protocol version"
	exit 1
}

log INFO "checking loopback-only HTTP health and authentication"
docker run -d --name "$container_name" --network bridge \
	-p "127.0.0.1::${HTTP_PORT}" \
	-e RANKRAT_HTTP_HOST=0.0.0.0 \
	-e RANKRAT_HTTP_PORT="$HTTP_PORT" \
	-e RANKRAT_ENABLE_OPENAPI=true \
	-e RANKRAT_HTTP_BEARER_SECRET_FILE=/run/secrets/test-http-bearer \
	"${container_security_args[@]}" "$image_reference" http >/dev/null
http_container_started=true

port_mapping=$(docker port "$container_name" "${HTTP_PORT}/tcp")
host_port="${port_mapping##*:}"
[[ "$host_port" =~ ^[0-9]+$ ]] || {
	log ERROR "Docker did not expose a numeric loopback port"
	exit 1
}
readonly health_url="http://127.0.0.1:${host_port}/healthz"
readonly ready_url="http://127.0.0.1:${host_port}/ready"
readonly openapi_url="http://127.0.0.1:${host_port}${OPENAPI_PATH}"
readonly schema_validate_url="http://127.0.0.1:${host_port}${SCHEMA_VALIDATE_URL_PATH}"

for ((attempt = 1; attempt <= HTTP_RETRY_COUNT; attempt++)); do
	if health_body=$(curl --silent --show-error --fail --noproxy '*' --proto '=http' \
		--max-redirs 0 --connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
		--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$health_url"); then
		break
	fi
	if [[ "$attempt" -eq "$HTTP_RETRY_COUNT" ]]; then
		log ERROR "HTTP health endpoint did not become ready"
		log_http_container_output
		exit 1
	fi
	sleep 1
done

grep -Fq '"ok":true' <<<"$health_body" || {
	log ERROR "HTTP health endpoint did not report ok"
	exit 1
}

unauthorized_status=$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$ready_url")
[[ "$unauthorized_status" == "401" ]] || {
	log ERROR "protected ready endpoint accepted an unauthenticated request"
	exit 1
}

authorized_ready_body=$(curl --silent --show-error --fail --config "$curl_authorization_config" \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$ready_url")
grep -Fq '"ready":true' <<<"$authorized_ready_body" || {
	log ERROR "protected ready endpoint did not accept the configured bearer secret"
	exit 1
}

unauthorized_openapi_status=$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$openapi_url")
[[ "$unauthorized_openapi_status" == "401" ]] || {
	log ERROR "OpenAPI endpoint accepted an unauthenticated request"
	exit 1
}

openapi_body=$(curl --silent --show-error --fail --config "$curl_authorization_config" \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$openapi_url")
grep -Fq "\"openapi\":\"$OPENAPI_VERSION\"" <<<"$openapi_body" || {
	log ERROR "production image did not publish an OAS 3.1 document"
	exit 1
}
grep -Fq "\"operationId\":\"$SERVER_INFO_OPERATION_ID\"" <<<"$openapi_body" || {
	log ERROR "production image did not publish YAML-owned operation IDs"
	exit 1
}

private_schema_response=$(curl --silent --show-error --config "$curl_authorization_config" \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" --request POST \
	--header 'Content-Type: application/json' \
	--data "$PRIVATE_SCHEMA_URL_REQUEST" "$schema_validate_url")
grep -Fq '"code":"REQUEST_REJECTED"' <<<"$private_schema_response" || {
	log ERROR "public schema validation did not reject a loopback target"
	exit 1
}

log INFO "checking unbounded HTTP startup permits the persisted-boundary writer"
docker rm -f "$container_name" >/dev/null
http_container_started=false
chmod 700 "$config_directory"
chmod 600 "$boundary_file"
container_name="rankrat-final-image-unbounded-$$-${RANDOM}"
docker run -d --name "$container_name" --network bridge \
	-p "127.0.0.1::${HTTP_PORT}" \
	--init --user "$TEST_CONTAINER_UID_GID" --read-only --cap-drop=ALL \
	--security-opt no-new-privileges:true --pids-limit "$TEST_PIDS_LIMIT" \
	--memory "$TEST_MEMORY_LIMIT" --cpus "$TEST_CPU_LIMIT" \
	--tmpfs "/tmp:rw,noexec,nosuid,size=32m" \
	--mount "type=bind,src=$config_directory,dst=/run/config" \
	--mount "type=bind,src=$secret_directory,dst=/run/secrets,readonly" \
	--mount "type=bind,src=$oauth_directory,dst=/run/oauth,readonly" \
	-e RANKRAT_BOUNDARY_FILE=/run/config/boundaries.json \
	-e RANKRAT_SECRET_ROOT=/run/secrets \
	-e RANKRAT_OAUTH_TOKEN_ROOT=/run/oauth \
	-e RANKRAT_HTTP_HOST=0.0.0.0 \
	-e RANKRAT_HTTP_PORT="$HTTP_PORT" \
	-e RANKRAT_HTTP_BEARER_SECRET_FILE=/run/secrets/test-http-bearer \
	-e RANKRAT_READ_ONLY=false \
	-e RANKRAT_UNBOUNDED=true \
	-e RANKRAT_ENABLE_OPENAPI=true \
	"$image_reference" http >/dev/null
http_container_started=true

unbounded_port_mapping=$(docker port "$container_name" "${HTTP_PORT}/tcp")
unbounded_host_port="${unbounded_port_mapping##*:}"
[[ "$unbounded_host_port" =~ ^[0-9]+$ ]] || {
	log ERROR "Docker did not expose a numeric unbounded loopback port"
	exit 1
}
readonly unbounded_health_url="http://127.0.0.1:${unbounded_host_port}/healthz"
readonly unbounded_server_info_url="http://127.0.0.1:${unbounded_host_port}${SERVER_INFO_URL_PATH}"
readonly unbounded_openapi_url="http://127.0.0.1:${unbounded_host_port}${OPENAPI_PATH}"

for ((attempt = 1; attempt <= HTTP_RETRY_COUNT; attempt++)); do
	if curl --silent --show-error --fail --noproxy '*' --proto '=http' \
		--max-redirs 0 --connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
		--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$unbounded_health_url" >/dev/null; then
		break
	fi
	if [[ "$attempt" -eq "$HTTP_RETRY_COUNT" ]]; then
		log ERROR "unbounded HTTP health endpoint did not become ready"
		log_http_container_output
		exit 1
	fi
	sleep 1
done

unbounded_server_info=$(curl --silent --show-error --fail --config "$curl_authorization_config" \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$unbounded_server_info_url")
grep -Fq '"read_only":false' <<<"$unbounded_server_info" || {
	log ERROR "unbounded server did not expose writable capability"
	exit 1
}
grep -Fq '"unbounded":true' <<<"$unbounded_server_info" || {
	log ERROR "unbounded server did not report active unbounded capability"
	exit 1
}

unbounded_openapi=$(curl --silent --show-error --fail --config "$curl_authorization_config" \
	--noproxy '*' --proto '=http' --max-redirs 0 \
	--connect-timeout "$HTTP_CONNECT_TIMEOUT_SECONDS" \
	--max-time "$HTTP_CONNECT_TIMEOUT_SECONDS" "$unbounded_openapi_url")
grep -Fq "\"${SITE_ONBOARDING_URL_PATH}\"" <<<"$unbounded_openapi" || {
	log ERROR "unbounded server did not publish the site onboarding route"
	exit 1
}

log INFO "production image stdio and HTTP smoke passed"
