"""Cross-package constants for Rankrat's foundation."""

from __future__ import annotations

from pathlib import Path

APP_NAME = "rankrat"
DEFAULT_HTTP_HOST = "127.0.0.1"
DEFAULT_HTTP_PORT = 8080
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_BOUNDARY_FILE = Path("/run/config/boundaries.json")
DEFAULT_SECRET_ROOT = Path("/run/secrets")
DEFAULT_OAUTH_TOKEN_ROOT = Path("/run/oauth")
OAUTH_LOOPBACK_HOST = "127.0.0.1"
OAUTH_CONTAINER_LISTENER_HOST = "0.0.0.0"  # nosec B104  # noqa: S104
OAUTH_DYNAMIC_CALLBACK_PORT = 0
DEFAULT_LOG_FILE = Path("/tmp/rankrat/rankrat.log")  # nosec B108  # noqa: S108
MAX_BOUNDARY_FILE_BYTES = 1_048_576
MAX_HTTP_BODY_BYTES = 1_048_576
MIN_HTTP_STATUS_CODE = 100
MAX_HTTP_STATUS_CODE = 599
MAX_PROVIDER_RESPONSE_BYTES = 2_097_152
MAX_PROVIDER_ITEMS = 1_000
MAX_ANALYTICS_ROWS = 1_000
MAX_ANALYTICS_OFFSET = 100_000
MAX_ANALYTICS_DIMENSIONS = 5
MAX_ANALYTICS_FILTERS = 20
MAX_ANALYTICS_FILTER_EXPRESSION_CHARS = 4_096
MAX_SEARCH_CONSOLE_TEXT_CHARS = 2_048
MAX_ANALYTICS_DATE_RANGE_DAYS = 366
MAX_SEARCH_ANALYTICS_DERIVED_ROWS = 500
MIN_SEARCH_ANALYTICS_ANOMALY_POINTS = 3
SEARCH_ANALYTICS_ANOMALY_Z_SCORE = 2.0
MAX_URL_INSPECTION_BATCH = 20
MAX_GA4_DATE_RANGES = 4
MAX_GA4_DIMENSIONS = 9
MAX_GA4_METRICS = 10
MAX_GA4_FIELD_NAME_CHARS = 128
MAX_GA4_VALUE_CHARS = 2_048
MAX_GA4_ROWS = 1_000
MAX_GA4_OFFSET = 100_000
GOOGLE_ANALYTICS_DISCOVERY_PAGE_SIZE = 200
MAX_GOOGLE_ANALYTICS_DISCOVERY_PAGES = 5
MIN_GA4_FUNNEL_STEPS = 2
MAX_GA4_FUNNEL_STEPS = 10
GA4_CONTENT_PERFORMANCE_DIMENSIONS = ("pagePathPlusQueryString",)
GA4_LANDING_PAGE_PERFORMANCE_DIMENSIONS = ("landingPagePlusQueryString",)
GA4_ORGANIC_SEARCH_LANDING_PAGE_DIMENSIONS = ("landingPagePlusQueryString",)
GA4_TRAFFIC_SOURCE_PERFORMANCE_DIMENSIONS = ("sessionSourceMedium",)
GA4_ECOMMERCE_PERFORMANCE_DIMENSIONS = ("itemName",)
GA4_AUDIENCE_SEGMENT_DIMENSIONS = ("audienceName",)
GA4_USER_BEHAVIOR_DIMENSIONS = ("newVsReturning",)
GA4_CONTENT_PERFORMANCE_METRICS = ("screenPageViews", "activeUsers", "engagedSessions")
GA4_LANDING_PAGE_PERFORMANCE_METRICS = ("sessions", "activeUsers", "engagedSessions")
GA4_ORGANIC_SEARCH_LANDING_PAGE_METRICS = (
    "organicGoogleSearchClicks",
    "organicGoogleSearchImpressions",
    "organicGoogleSearchClickThroughRate",
    "organicGoogleSearchAveragePosition",
)
GA4_TRAFFIC_SOURCE_PERFORMANCE_METRICS = ("sessions", "activeUsers", "engagedSessions")
GA4_ECOMMERCE_PERFORMANCE_METRICS = ("itemsPurchased", "itemsViewed", "itemRevenue")
GA4_AUDIENCE_SEGMENT_METRICS = ("activeUsers", "newUsers", "engagedSessions")
GA4_USER_BEHAVIOR_METRICS = ("activeUsers", "newUsers", "engagedSessions")
GA4_PAGESPEED_CORRELATION_OPERATION = "ga4_pagespeed_correlation"
GA4_PAGESPEED_CORRELATION_PATH = "/cross-provider/ga4-pagespeed-correlations"
GOOGLE_ANALYTICS_ACCOUNT_INVENTORY_OPERATION = "google_analytics_account_inventory"
GOOGLE_ANALYTICS_ACCOUNT_INVENTORY_PATH = "/google-analytics/account-inventory"
GOOGLE_ANALYTICS_DATA_STREAMS_OPERATION = "google_analytics_data_streams"
GOOGLE_ANALYTICS_DATA_STREAMS_PATH = "/google-analytics/data-streams"
GOOGLE_ANALYTICS_ACCOUNT_RENAME_OPERATION = "google_analytics_account_rename"
GOOGLE_ANALYTICS_ACCOUNT_RENAME_PATH = "/google-analytics/account-renames"
GOOGLE_ANALYTICS_PROPERTY_RENAME_OPERATION = "google_analytics_property_rename"
GOOGLE_ANALYTICS_PROPERTY_RENAME_PATH = "/google-analytics/property-renames"
SEARCH_ENGINE_COMPARISON_OPERATION = "search_engine_comparison"
SEARCH_ENGINE_COMPARISON_PATH = "/cross-provider/search-engine-comparisons"
GA4_SEARCH_CONSOLE_COMPARISON_OPERATION = "ga4_search_console_comparison"
GA4_SEARCH_CONSOLE_COMPARISON_PATH = "/cross-provider/ga4-search-console-comparisons"
SEARCH_ENGINE_TRAFFIC_HEALTH_OPERATION = "search_engine_traffic_health"
SEARCH_ENGINE_TRAFFIC_HEALTH_PATH = "/cross-provider/search-engine-traffic-health"
PAGESPEED_CORE_WEB_VITALS_OPERATION = "pagespeed_core_web_vitals"
PAGESPEED_CORE_WEB_VITALS_PATH = "/pagespeed/core-web-vitals"
PAGESPEED_LARGEST_CONTENTFUL_PAINT_METRIC_IDS = (
    "LARGEST_CONTENTFUL_PAINT_MS",
    "LARGEST_CONTENTFUL_PAINT",
)
PAGESPEED_CUMULATIVE_LAYOUT_SHIFT_METRIC_IDS = (
    "CUMULATIVE_LAYOUT_SHIFT_SCORE",
    "CUMULATIVE_LAYOUT_SHIFT",
)
PAGESPEED_INTERACTION_TO_NEXT_PAINT_METRIC_IDS = (
    "INTERACTION_TO_NEXT_PAINT",
    "INTERACTION_TO_NEXT_PAINT_MS",
)
MAX_BING_QUERY_CHARS = 256
MAX_BING_BRAND_TERMS = 20
MAX_BING_BRAND_TERM_CHARS = 128
MAX_BING_STATS_LABEL_CHARS = 2_048
MAX_BING_COUNTRY_CHARS = 16
MAX_BING_LANGUAGE_CHARS = 32
MAX_BING_SUBMISSION_URLS = 500
MAX_BING_LINK_PAGE = 1_000
MAX_BING_TRAFFIC_DATE_RANGE_DAYS = 366
MIN_BING_TRAFFIC_ANOMALY_POINTS = 3
BING_TRAFFIC_ANOMALY_Z_SCORE = 2.0
MAX_BING_DERIVED_OPPORTUNITIES = 500
BING_UNKNOWN_AVERAGE_POSITION = -1.0
BING_OPPORTUNITY_MATRIX_OPERATION = "bing_opportunity_matrix"
BING_OPPORTUNITY_MATRIX_PATH = "/bing/opportunity-matrix"
BING_STRIKING_DISTANCE_MIN_POSITION = 4.0
BING_STRIKING_DISTANCE_MAX_POSITION = 20.0
BING_TOP_THREE_MAX_AVERAGE_CLICK_POSITION = 3.0
BING_FIRST_PAGE_MAX_AVERAGE_CLICK_POSITION = 10.0
BING_SECOND_PAGE_MAX_AVERAGE_CLICK_POSITION = 20.0
MAX_GOOGLE_INDEXING_BATCH = 100
MAX_GOOGLE_INDEXING_BATCH_PART_RESPONSE_BYTES = 65_536
MAX_GOOGLE_INDEXING_TEXT_CHARS = 2_048
MAX_OAUTH_TOKEN_FILE_BYTES = 32_768
MAX_PAGESPEED_CATEGORIES = 5
MAX_PAGESPEED_LOADING_EXPERIENCE_METRICS = 16
MAX_PAGESPEED_METRIC_DISTRIBUTIONS = 8
MAX_PAGESPEED_METRIC_ID_CHARS = 128
MAX_PAGESPEED_METRIC_CATEGORY_CHARS = 32
MAX_PAGESPEED_METRIC_VALUE = 2_147_483_647
PAGESPEED_DISTRIBUTION_PROPORTION_TOLERANCE = 0.000_001
MAX_INDEXNOW_URLS = 1_000
MAX_APPROVAL_ID_CHARS = 256
MAX_SCHEMA_FETCH_URL_CHARS = 2_048
MAX_SCHEMA_FETCH_RESPONSE_BYTES = 1_048_576
MAX_SCHEMA_LOCAL_DOCUMENT_CHARS = 1_048_576
MAX_SCHEMA_JSON_DEPTH = 32
MAX_SCHEMA_JSON_ITEMS = 10_000
MAX_SCHEMA_JSON_LD_SCRIPTS = 64
MAX_SCHEMA_JSON_LD_SCRIPT_BYTES = 65_536
DEFAULT_PROVIDER_TIMEOUT_SECONDS = 10.0
MIN_PROVIDER_TIMEOUT_SECONDS = 0.1
MAX_PROVIDER_TIMEOUT_SECONDS = 30.0
DEFAULT_PAGESPEED_TIMEOUT_SECONDS = MAX_PROVIDER_TIMEOUT_SECONDS
MAX_LOG_BYTES = 10_000_000
LOG_BACKUP_COUNT = 3
MAX_REDACTION_DEPTH = 8
HTTP_BEARER_PREFIX = "Bearer "
HEALTH_PATH = "/healthz"
MCP_PATH = "/mcp"
API_PREFIX = "/v1"
INDEXNOW_ENDPOINT_URL = "https://api.indexnow.org/indexnow"
GOOGLE_SEARCH_CONSOLE_READ_SCOPE = "https://www.googleapis.com/auth/webmasters.readonly"
GOOGLE_SEARCH_CONSOLE_WRITE_SCOPE = "https://www.googleapis.com/auth/webmasters"
GOOGLE_INDEXING_SCOPE = "https://www.googleapis.com/auth/indexing"
GOOGLE_ANALYTICS_READ_SCOPE = "https://www.googleapis.com/auth/analytics.readonly"
GOOGLE_ANALYTICS_EDIT_SCOPE = "https://www.googleapis.com/auth/analytics.edit"
MAX_SITE_ONBOARDING_DISPLAY_NAME_CHARS = 100
MAX_SITE_ONBOARDING_TIME_ZONE_CHARS = 64
ISO_CURRENCY_CODE_CHARS = 3
